### ISSUE TITLE
Handle Github rate limit

### ISSUE THREAD

**Issue by jcmrva** [unisonweb/elm-browser#2]
It may not come up in ordinary use but it might be a good idea to surface this in the UI.

![image](https://user-images.githubusercontent.com/20140997/63216876-29679a00-c10a-11e9-8364-dd00ebd58fec.png)

**Comment by pchiusano** [comment]
Is this relevant if you are grabbing content via, for example: https://raw.githubusercontent.com/unisonweb/elm-browser/master/src/Deserialize.elm or https://github.com/unisonweb/unisonbase/blob/master/.unison/v1/paths/0c3ad476251ft7dnbdiq870bj4es0vtlev2u5i4jts022mgjjnugod2sdcqli53503i21vrtim35j6pqncm2g9mglghv8aod070e5cg.ub?raw=true

Like is there still a rate limit for regular GET requests of repository files? And/or are you discouraged from using those endpoints for scripts / programs?

**Comment by aryairani** [comment]
I would think it’s for the “api...” endpoints but not sure.  Also probably not an issue if you’re signed into github in your browser, but not certain.

**Comment by mitchellwrosen** [comment]
Good point @jcmrva. I think that makes the simple plan of just fetching files one-by-one from GitHub somewhat DOA. It's possible to work around the rate limit by logging in, but this would require quite a bit of ceremony (esp. if you have 2fa enabled). Seems like we should pursue a different path :)

**Comment by jcmrva** [comment]
I'm going to close this for now as it looks like accessing the raw files per Paul's suggestion will work.
