### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by BenFradet** [unisonweb/elm-browser#54]
Hey, I tried following the guide in the readme by:

- running `elm make client-src/Main.elm --output main.js` (I have elm 0.19.0 installed)
- running `stack install`
- running `unison-browser` in a dir with a unison codebase

When I try accessing the browser from firefox, I get:

```
SyntaxError: expected expression, got '<'
main.js:1
ReferenceError: Elm is not defined127.0.0.1:8180:12:13
    <anonymous> http://127.0.0.1:8180/:12
```

in the console.

Any ideas what I'm doing wrong?

**Comment by ashishsc** [comment]
Sorry about that, looks like we just broke it! Fixed in https://github.com/unisonweb/elm-browser/pull/55

**Comment by BenFradet** [comment]
excellent thanks!
