### ISSUE TITLE
Can't see all definitions in my codebase

### ISSUE THREAD

**Issue by xilnocas** [unisonweb/elm-browser#59]
If I navigate to `.` in my unison shell and run `ls`, I get the following
```
.> ls

  1. base/      (470 definitions)
  2. builtin/   (265 definitions)
  3. hobbits/   (8 definitions)
  4. lib/       (80 definitions)
  5. mylibrary/ (8 definitions)
```

However, here's what the browser looks like after initial load

![image](https://user-images.githubusercontent.com/5252770/68552981-30d9cf00-03eb-11ea-9f73-1dfec1c157e5.png)

It's rendering everything as if it's`cd`'d into `.builtin`, and even then namespaces within `.builtin` aren't showing up

**Comment by xilnocas** [comment]
Hm, I cloned my unison monorepo into a new directory, ran the browser on it, and got this

![image](https://user-images.githubusercontent.com/5252770/68563103-89749080-041a-11ea-9a5e-2371d74ecf02.png)

I've confirmed that the `head` is different in the two directories

I'm also extremely fuzzy on what branches and and head even are... could be user error

**Comment by xilnocas** [comment]
@seagreen figured it out!

I didn't know that my `ucm` session was attached to the `.unision`directory in my home directory ... I didn't know that was the default!

I assumed it was reading `.unison` from my current directory, which is what the `unison-browser` server was doing.

**Comment by mitchellwrosen** [comment]
That's odd... seems like a bug in `ucm` to me. I'd expect local `./.unison` to have precedence over `~/.unison`. Maybe file an issue or ask about it in Slack?
